name: "\U0001F41B Bug report"
description: Create a report to improve Spotify-Cards-API
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.

        This issue tracker is for bugs and issues found within Spotify-Cards-API Project.

        Please fill in as much of the form below as you're able.
  - type: input
    attributes:
      label: Version
      description: Output of `node -v`
  - type: input
    attributes:
      label: Platform
      description: |
        UNIX: output of `uname -a`
        Windows: output of `"$([Environment]::OSVersion | ForEach-Object VersionString) $(if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" })"` in PowerShell console
  - type: textarea
    attributes:
      label: What steps will reproduce the bug?
      description: Enter details about your bug.
  - type: textarea
    attributes:
      label: How often does it reproduce? Is there a required condition?
  - type: textarea
    attributes:
      label: Is there any Package conflicting with other packages?
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: What do you see instead?
      description: If possible please provide textual output instead of screenshots.
  - type: textarea
    attributes:
      label: Additional information
      description: Tell us anything else you think we should know.
# Template taken from NodeJs Repository
